# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: manchy
  tag: v1.0.2-e321bac
  arch: amd64
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
securityContext:
  privileged: true